/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package unit.br.edu.claudivan.cleanarch

import kotlin.test.Test
import kotlin.test.assertNotNull
import br.edu.claudivan.cleanarch.Application

class AppTest {
    @Test fun appHasAGreeting() {
        val classUnderTest = Application()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
